# Prometheus configuration for ServerChat monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Main Server monitoring
  - job_name: 'main-server'
    static_configs:
      - targets: ['main-server:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Chat Servers monitoring
  - job_name: 'chat-servers'
    static_configs:
      - targets: 
        - 'chat-server-general:8080'
        - 'chat-server-gaming:8080'
        - 'chat-server-study:8080'
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MongoDB monitoring (requires mongodb_exporter)
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Redis monitoring (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx monitoring (requires nginx-prometheus-exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "http://remote-storage:9201/write"